// List<Order> orders = [SELECT Id FROM Order WHERE Status = 'In Packing'];
// delete orders;
// OrderItem orders = [SELECT Id FROM OrderItem WHERE Id = '802Qy0000015k01IAA'];
// system.debug('Item: ' + orders);
// Order orders = [SELECT Id, TotalQuantity__c FROM Order WHERE Id = '801Qy00000DEhX5IAL'];
// system.debug('Item: ' + orders);
// EmailTemplate et = [SELECT Id, Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Brewed_Elixirs_Summary'];
// system.debug('et: ' + et);
